
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/org.freewb.desktop.in ${CMAKE_CURRENT_BINARY_DIR}/org.freewb.desktop IMMEDIATE @ONLY)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/org.freewb.desktop DESTINATION /etc/xdg/autostart )

configure_file(${CMAKE_CURRENT_SOURCE_DIR}/org.freewb.start.sh.in ${CMAKE_CURRENT_BINARY_DIR}/org.freewb.start.sh IMMEDIATE @ONLY)
install(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/org.freewb.start.sh DESTINATION ${FREEWB_INSTALL_BINDIR}/)

configure_file(${CMAKE_CURRENT_SOURCE_DIR}/config.ini.in ${CMAKE_CURRENT_BINARY_DIR}/config.ini IMMEDIATE @ONLY)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/config.ini DESTINATION ${FREEWB_INSTALL_PKGDATADIR}/config)

install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/dict DESTINATION ${FREEWB_INSTALL_PKGDATADIR}/data)
install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/mb DESTINATION ${FREEWB_INSTALL_PKGDATADIR}/data)

configure_file(${CMAKE_CURRENT_SOURCE_DIR}/s2t/s2t.json.in ${CMAKE_CURRENT_BINARY_DIR}/s2t.json IMMEDIATE @ONLY)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/s2t.json DESTINATION ${FREEWB_INSTALL_PKGDATADIR}/data/s2t)

install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/quick_table.txt DESTINATION ${FREEWB_INSTALL_PKGDATADIR}/data)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/user_word.txt DESTINATION ${FREEWB_INSTALL_PKGDATADIR}/data)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/setting_tips.txt DESTINATION ${FREEWB_INSTALL_PKGDATADIR}/data)
