
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/org.freewb.desktop.in ${CMAKE_CURRENT_BINARY_DIR}/org.freewb.desktop IMMEDIATE @ONLY)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/org.freewb.desktop DESTINATION /etc/xdg/autostart )

configure_file(${CMAKE_CURRENT_SOURCE_DIR}/org.freewb.start.sh.in ${CMAKE_CURRENT_BINARY_DIR}/org.freewb.start.sh IMMEDIATE @ONLY)
install(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/org.freewb.start.sh DESTINATION ${FREEWB_INSTALL_BINDIR}/)

configure_file(${CMAKE_CURRENT_SOURCE_DIR}/org.freewb.panel.service.in ${CMAKE_CURRENT_BINARY_DIR}/org.freewb.panel.service IMMEDIATE @ONLY)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/org.freewb.panel.service DESTINATION ${FREEWB_INSTALL_DATADIR}/dbus-1/services)

install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/dict DESTINATION ${FREEWB_INSTALL_PKGDATADIR}/data)
install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/mb DESTINATION ${FREEWB_INSTALL_PKGDATADIR}/data)

configure_file(${CMAKE_CURRENT_SOURCE_DIR}/s2t/s2t.json.in ${CMAKE_CURRENT_BINARY_DIR}/s2t.json IMMEDIATE @ONLY)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/s2t.json DESTINATION ${FREEWB_INSTALL_PKGDATADIR}/s2t)

install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/quick_table.txt DESTINATION ${FREEWB_INSTALL_PKGDATADIR}/data)
